name: Build

on:
  push:
    branches:
    - master
    - develop
    - feature/*
  pull_request:
    branches:
    - develop

# macOS environments: https://github.com/actions/virtual-environments/tree/main/images/macos

jobs:
  build:
    name: Build
    runs-on: macos-12
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        id: deployment
        with:
          token: '${{ github.token }}'
          environment-url: https://github.com/MainasuK/DeadPixelTest/tags
          environment: staging

      - name: Update deployment status (in_progress)
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'in_progress'
        
      - name: setup
        run: exec ./.github/scripts/setup.sh

      - name: build
        run: exec ./.github/scripts/build.sh

      - name: Tag commit
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: "${{ env.GITHUB_TAG_NAME }}"

      - name: Update deployment status (success)
        if: ${{ success() }}
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: https://github.com/MainasuK/DeadPixelTest/releases/tag/${{ env.GITHUB_TAG_NAME }}
          log-url: https://github.com/MainasuK/DeadPixelTest/releases/tag/${{ env.GITHUB_TAG_NAME }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'success'

      - name: Update deployment status (failure)
        if: ${{ failure() }}
        uses: chrnorm/deployment-status@v2
        with:
          token: '${{ github.token }}'
          environment-url: ${{ steps.deployment.outputs.environment_url }}
          deployment-id: ${{ steps.deployment.outputs.deployment_id }}
          state: 'failure'
